#include "base.h"
//
//Given two strings s and t which consist of only lowercase letters. 
//
// String t is generated by random shuffling string s and then add one more lett
//er at a random position. 
//
// Find the letter that was added in t. 
//
// Example:
// 
//Input:
//s = "abcd"
//t = "abcde"
//
//Output:
//e
//
//Explanation:
//'e' is the letter that was added.
// Related Topics Hash Table Bit Manipulation 
// 👍 819 👎 283


//leetcode submit region begin(Prohibit modification and deletion)
class Solution {
public:
    char findTheDifference(string const& s, string const& t) {
        auto bits = array<int, 26>();
        for (auto c : s) {
            ++bits[c - 'a'];
        }
        for (auto c : t) {
            if (--bits[c - 'a'] < 0)
                return c;
        }
        return ' ';
    }
};
//leetcode submit region end(Prohibit modification and deletion)
